// Generated by gencpp from file handsfree_arm_msgs/ArmAction.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_ARMACTION_H
#define HANDSFREE_ARM_MSGS_MESSAGE_ARMACTION_H

#include <ros/service_traits.h>


#include <handsfree_arm_msgs/ArmActionRequest.h>
#include <handsfree_arm_msgs/ArmActionResponse.h>


namespace handsfree_arm_msgs
{

struct ArmAction
{

typedef ArmActionRequest Request;
typedef ArmActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmAction
} // namespace handsfree_arm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handsfree_arm_msgs::ArmAction > {
  static const char* value()
  {
    return "569569360f70adfcbf20282dd2e8e042";
  }

  static const char* value(const ::handsfree_arm_msgs::ArmAction&) { return value(); }
};

template<>
struct DataType< ::handsfree_arm_msgs::ArmAction > {
  static const char* value()
  {
    return "handsfree_arm_msgs/ArmAction";
  }

  static const char* value(const ::handsfree_arm_msgs::ArmAction&) { return value(); }
};


// service_traits::MD5Sum< ::handsfree_arm_msgs::ArmActionRequest> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::ArmAction > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::ArmActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::ArmAction >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::ArmActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::ArmActionRequest> should match 
// service_traits::DataType< ::handsfree_arm_msgs::ArmAction > 
template<>
struct DataType< ::handsfree_arm_msgs::ArmActionRequest>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::ArmAction >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::ArmActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handsfree_arm_msgs::ArmActionResponse> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::ArmAction > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::ArmActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::ArmAction >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::ArmActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::ArmActionResponse> should match 
// service_traits::DataType< ::handsfree_arm_msgs::ArmAction > 
template<>
struct DataType< ::handsfree_arm_msgs::ArmActionResponse>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::ArmAction >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::ArmActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_ARMACTION_H
