// Generated by gencpp from file handsfree_arm_msgs/ArmBehaviorFeedback.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_ARMBEHAVIORFEEDBACK_H
#define HANDSFREE_ARM_MSGS_MESSAGE_ARMBEHAVIORFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace handsfree_arm_msgs
{
template <class ContainerAllocator>
struct ArmBehaviorFeedback_
{
  typedef ArmBehaviorFeedback_<ContainerAllocator> Type;

  ArmBehaviorFeedback_()
    : feedback_bool(0.0)  {
    }
  ArmBehaviorFeedback_(const ContainerAllocator& _alloc)
    : feedback_bool(0.0)  {
  (void)_alloc;
    }



   typedef double _feedback_bool_type;
  _feedback_bool_type feedback_bool;





  typedef boost::shared_ptr< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ArmBehaviorFeedback_

typedef ::handsfree_arm_msgs::ArmBehaviorFeedback_<std::allocator<void> > ArmBehaviorFeedback;

typedef boost::shared_ptr< ::handsfree_arm_msgs::ArmBehaviorFeedback > ArmBehaviorFeedbackPtr;
typedef boost::shared_ptr< ::handsfree_arm_msgs::ArmBehaviorFeedback const> ArmBehaviorFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace handsfree_arm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'handsfree_arm_msgs': ['/home/handsfree/handsfree/handsfree_ros_ws/src/handsfree_arm/handsfree_arm_msgs/msg', '/home/handsfree/handsfree/handsfree_ros_ws/devel/share/handsfree_arm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adcf7c34a058504c0b38f31ca66f0395";
  }

  static const char* value(const ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadcf7c34a058504cULL;
  static const uint64_t static_value2 = 0x0b38f31ca66f0395ULL;
};

template<class ContainerAllocator>
struct DataType< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handsfree_arm_msgs/ArmBehaviorFeedback";
  }

  static const char* value(const ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback defin\n\
float64 feedback_bool\n\
\n\
";
  }

  static const char* value(const ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback_bool);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmBehaviorFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::handsfree_arm_msgs::ArmBehaviorFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback_bool: ";
    Printer<double>::stream(s, indent + "  ", v.feedback_bool);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_ARMBEHAVIORFEEDBACK_H
