// Generated by gencpp from file handsfree_arm_msgs/GeneratePoseRequest.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_GENERATEPOSEREQUEST_H
#define HANDSFREE_ARM_MSGS_MESSAGE_GENERATEPOSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <handsfree_arm_msgs/BoundingBox.h>
#include <std_msgs/String.h>
#include <sensor_msgs/Image.h>

namespace handsfree_arm_msgs
{
template <class ContainerAllocator>
struct GeneratePoseRequest_
{
  typedef GeneratePoseRequest_<ContainerAllocator> Type;

  GeneratePoseRequest_()
    : bounding_box()
    , gripper_type()
    , depth_image()  {
    }
  GeneratePoseRequest_(const ContainerAllocator& _alloc)
    : bounding_box(_alloc)
    , gripper_type(_alloc)
    , depth_image(_alloc)  {
  (void)_alloc;
    }



   typedef  ::handsfree_arm_msgs::BoundingBox_<ContainerAllocator>  _bounding_box_type;
  _bounding_box_type bounding_box;

   typedef  ::std_msgs::String_<ContainerAllocator>  _gripper_type_type;
  _gripper_type_type gripper_type;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _depth_image_type;
  _depth_image_type depth_image;





  typedef boost::shared_ptr< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GeneratePoseRequest_

typedef ::handsfree_arm_msgs::GeneratePoseRequest_<std::allocator<void> > GeneratePoseRequest;

typedef boost::shared_ptr< ::handsfree_arm_msgs::GeneratePoseRequest > GeneratePoseRequestPtr;
typedef boost::shared_ptr< ::handsfree_arm_msgs::GeneratePoseRequest const> GeneratePoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace handsfree_arm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'handsfree_arm_msgs': ['/home/handsfree/handsfree/handsfree_ros_ws/src/handsfree_arm/handsfree_arm_msgs/msg', '/home/handsfree/handsfree/handsfree_ros_ws/devel/share/handsfree_arm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6fb3f759371dd7cb77c09ef1bd9e881";
  }

  static const char* value(const ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6fb3f759371dd7cULL;
  static const uint64_t static_value2 = 0xb77c09ef1bd9e881ULL;
};

template<class ContainerAllocator>
struct DataType< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handsfree_arm_msgs/GeneratePoseRequest";
  }

  static const char* value(const ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handsfree_arm_msgs/BoundingBox bounding_box\n\
std_msgs/String gripper_type\n\
sensor_msgs/Image depth_image\n\
\n\
================================================================================\n\
MSG: handsfree_arm_msgs/BoundingBox\n\
float64 probability\n\
int64 xmin\n\
int64 ymin\n\
int64 xmax\n\
int64 ymax\n\
int16 id\n\
string Class\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bounding_box);
      stream.next(m.gripper_type);
      stream.next(m.depth_image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeneratePoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::handsfree_arm_msgs::GeneratePoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "bounding_box: ";
    s << std::endl;
    Printer< ::handsfree_arm_msgs::BoundingBox_<ContainerAllocator> >::stream(s, indent + "  ", v.bounding_box);
    s << indent << "gripper_type: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.gripper_type);
    s << indent << "depth_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.depth_image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_GENERATEPOSEREQUEST_H
