// Generated by gencpp from file handsfree_arm_msgs/GeneratePose.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_GENERATEPOSE_H
#define HANDSFREE_ARM_MSGS_MESSAGE_GENERATEPOSE_H

#include <ros/service_traits.h>


#include <handsfree_arm_msgs/GeneratePoseRequest.h>
#include <handsfree_arm_msgs/GeneratePoseResponse.h>


namespace handsfree_arm_msgs
{

struct GeneratePose
{

typedef GeneratePoseRequest Request;
typedef GeneratePoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GeneratePose
} // namespace handsfree_arm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handsfree_arm_msgs::GeneratePose > {
  static const char* value()
  {
    return "337278d1e16607c0ea6aa3812dd83c07";
  }

  static const char* value(const ::handsfree_arm_msgs::GeneratePose&) { return value(); }
};

template<>
struct DataType< ::handsfree_arm_msgs::GeneratePose > {
  static const char* value()
  {
    return "handsfree_arm_msgs/GeneratePose";
  }

  static const char* value(const ::handsfree_arm_msgs::GeneratePose&) { return value(); }
};


// service_traits::MD5Sum< ::handsfree_arm_msgs::GeneratePoseRequest> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::GeneratePose > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::GeneratePoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::GeneratePose >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::GeneratePoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::GeneratePoseRequest> should match 
// service_traits::DataType< ::handsfree_arm_msgs::GeneratePose > 
template<>
struct DataType< ::handsfree_arm_msgs::GeneratePoseRequest>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::GeneratePose >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::GeneratePoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handsfree_arm_msgs::GeneratePoseResponse> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::GeneratePose > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::GeneratePoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::GeneratePose >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::GeneratePoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::GeneratePoseResponse> should match 
// service_traits::DataType< ::handsfree_arm_msgs::GeneratePose > 
template<>
struct DataType< ::handsfree_arm_msgs::GeneratePoseResponse>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::GeneratePose >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::GeneratePoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_GENERATEPOSE_H
