// Generated by gencpp from file handsfree_arm_msgs/SetArmPath.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_SETARMPATH_H
#define HANDSFREE_ARM_MSGS_MESSAGE_SETARMPATH_H

#include <ros/service_traits.h>


#include <handsfree_arm_msgs/SetArmPathRequest.h>
#include <handsfree_arm_msgs/SetArmPathResponse.h>


namespace handsfree_arm_msgs
{

struct SetArmPath
{

typedef SetArmPathRequest Request;
typedef SetArmPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetArmPath
} // namespace handsfree_arm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handsfree_arm_msgs::SetArmPath > {
  static const char* value()
  {
    return "a11bc29d179f5cf591b41549055998a2";
  }

  static const char* value(const ::handsfree_arm_msgs::SetArmPath&) { return value(); }
};

template<>
struct DataType< ::handsfree_arm_msgs::SetArmPath > {
  static const char* value()
  {
    return "handsfree_arm_msgs/SetArmPath";
  }

  static const char* value(const ::handsfree_arm_msgs::SetArmPath&) { return value(); }
};


// service_traits::MD5Sum< ::handsfree_arm_msgs::SetArmPathRequest> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::SetArmPath > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::SetArmPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::SetArmPath >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetArmPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::SetArmPathRequest> should match 
// service_traits::DataType< ::handsfree_arm_msgs::SetArmPath > 
template<>
struct DataType< ::handsfree_arm_msgs::SetArmPathRequest>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::SetArmPath >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetArmPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handsfree_arm_msgs::SetArmPathResponse> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::SetArmPath > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::SetArmPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::SetArmPath >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetArmPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::SetArmPathResponse> should match 
// service_traits::DataType< ::handsfree_arm_msgs::SetArmPath > 
template<>
struct DataType< ::handsfree_arm_msgs::SetArmPathResponse>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::SetArmPath >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetArmPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_SETARMPATH_H
