// Generated by gencpp from file handsfree_arm_msgs/SetFloat32.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_SETFLOAT32_H
#define HANDSFREE_ARM_MSGS_MESSAGE_SETFLOAT32_H

#include <ros/service_traits.h>


#include <handsfree_arm_msgs/SetFloat32Request.h>
#include <handsfree_arm_msgs/SetFloat32Response.h>


namespace handsfree_arm_msgs
{

struct SetFloat32
{

typedef SetFloat32Request Request;
typedef SetFloat32Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloat32
} // namespace handsfree_arm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handsfree_arm_msgs::SetFloat32 > {
  static const char* value()
  {
    return "67f314fe2a20c481af1737f0d9630453";
  }

  static const char* value(const ::handsfree_arm_msgs::SetFloat32&) { return value(); }
};

template<>
struct DataType< ::handsfree_arm_msgs::SetFloat32 > {
  static const char* value()
  {
    return "handsfree_arm_msgs/SetFloat32";
  }

  static const char* value(const ::handsfree_arm_msgs::SetFloat32&) { return value(); }
};


// service_traits::MD5Sum< ::handsfree_arm_msgs::SetFloat32Request> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::SetFloat32 > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::SetFloat32Request>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::SetFloat32 >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetFloat32Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::SetFloat32Request> should match 
// service_traits::DataType< ::handsfree_arm_msgs::SetFloat32 > 
template<>
struct DataType< ::handsfree_arm_msgs::SetFloat32Request>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::SetFloat32 >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetFloat32Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handsfree_arm_msgs::SetFloat32Response> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::SetFloat32 > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::SetFloat32Response>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::SetFloat32 >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetFloat32Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::SetFloat32Response> should match 
// service_traits::DataType< ::handsfree_arm_msgs::SetFloat32 > 
template<>
struct DataType< ::handsfree_arm_msgs::SetFloat32Response>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::SetFloat32 >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetFloat32Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_SETFLOAT32_H
