// Generated by gencpp from file handsfree_arm_msgs/SetJointsPosition.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTSPOSITION_H
#define HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTSPOSITION_H

#include <ros/service_traits.h>


#include <handsfree_arm_msgs/SetJointsPositionRequest.h>
#include <handsfree_arm_msgs/SetJointsPositionResponse.h>


namespace handsfree_arm_msgs
{

struct SetJointsPosition
{

typedef SetJointsPositionRequest Request;
typedef SetJointsPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointsPosition
} // namespace handsfree_arm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handsfree_arm_msgs::SetJointsPosition > {
  static const char* value()
  {
    return "777e2ee80fd7c45ba565ea77ca6c48db";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointsPosition&) { return value(); }
};

template<>
struct DataType< ::handsfree_arm_msgs::SetJointsPosition > {
  static const char* value()
  {
    return "handsfree_arm_msgs/SetJointsPosition";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointsPosition&) { return value(); }
};


// service_traits::MD5Sum< ::handsfree_arm_msgs::SetJointsPositionRequest> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::SetJointsPosition > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::SetJointsPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::SetJointsPosition >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetJointsPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::SetJointsPositionRequest> should match 
// service_traits::DataType< ::handsfree_arm_msgs::SetJointsPosition > 
template<>
struct DataType< ::handsfree_arm_msgs::SetJointsPositionRequest>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::SetJointsPosition >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetJointsPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handsfree_arm_msgs::SetJointsPositionResponse> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::SetJointsPosition > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::SetJointsPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::SetJointsPosition >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetJointsPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::SetJointsPositionResponse> should match 
// service_traits::DataType< ::handsfree_arm_msgs::SetJointsPosition > 
template<>
struct DataType< ::handsfree_arm_msgs::SetJointsPositionResponse>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::SetJointsPosition >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetJointsPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTSPOSITION_H
