// Generated by gencpp from file handsfree_arm_msgs/SetJointPosition.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTPOSITION_H
#define HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTPOSITION_H

#include <ros/service_traits.h>


#include <handsfree_arm_msgs/SetJointPositionRequest.h>
#include <handsfree_arm_msgs/SetJointPositionResponse.h>


namespace handsfree_arm_msgs
{

struct SetJointPosition
{

typedef SetJointPositionRequest Request;
typedef SetJointPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointPosition
} // namespace handsfree_arm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handsfree_arm_msgs::SetJointPosition > {
  static const char* value()
  {
    return "24a0e6df4d9002524b50ba13f5c1f307";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointPosition&) { return value(); }
};

template<>
struct DataType< ::handsfree_arm_msgs::SetJointPosition > {
  static const char* value()
  {
    return "handsfree_arm_msgs/SetJointPosition";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointPosition&) { return value(); }
};


// service_traits::MD5Sum< ::handsfree_arm_msgs::SetJointPositionRequest> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::SetJointPosition > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::SetJointPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::SetJointPosition >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetJointPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::SetJointPositionRequest> should match 
// service_traits::DataType< ::handsfree_arm_msgs::SetJointPosition > 
template<>
struct DataType< ::handsfree_arm_msgs::SetJointPositionRequest>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::SetJointPosition >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetJointPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handsfree_arm_msgs::SetJointPositionResponse> should match 
// service_traits::MD5Sum< ::handsfree_arm_msgs::SetJointPosition > 
template<>
struct MD5Sum< ::handsfree_arm_msgs::SetJointPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_arm_msgs::SetJointPosition >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetJointPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_arm_msgs::SetJointPositionResponse> should match 
// service_traits::DataType< ::handsfree_arm_msgs::SetJointPosition > 
template<>
struct DataType< ::handsfree_arm_msgs::SetJointPositionResponse>
{
  static const char* value()
  {
    return DataType< ::handsfree_arm_msgs::SetJointPosition >::value();
  }
  static const char* value(const ::handsfree_arm_msgs::SetJointPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTPOSITION_H
