// Generated by gencpp from file handsfree_arm_msgs/SetJointsPositionRequest.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTSPOSITIONREQUEST_H
#define HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTSPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <handsfree_arm_msgs/arm_joints_position.h>

namespace handsfree_arm_msgs
{
template <class ContainerAllocator>
struct SetJointsPositionRequest_
{
  typedef SetJointsPositionRequest_<ContainerAllocator> Type;

  SetJointsPositionRequest_()
    : data()  {
    }
  SetJointsPositionRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::handsfree_arm_msgs::arm_joints_position_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointsPositionRequest_

typedef ::handsfree_arm_msgs::SetJointsPositionRequest_<std::allocator<void> > SetJointsPositionRequest;

typedef boost::shared_ptr< ::handsfree_arm_msgs::SetJointsPositionRequest > SetJointsPositionRequestPtr;
typedef boost::shared_ptr< ::handsfree_arm_msgs::SetJointsPositionRequest const> SetJointsPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace handsfree_arm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'handsfree_arm_msgs': ['/home/handsfree/handsfree/handsfree_ros_ws/src/handsfree_arm/handsfree_arm_msgs/msg', '/home/handsfree/handsfree/handsfree_ros_ws/devel/share/handsfree_arm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "877d0619442855790b252518e4ee2740";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x877d061944285579ULL;
  static const uint64_t static_value2 = 0x0b252518e4ee2740ULL;
};

template<class ContainerAllocator>
struct DataType< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handsfree_arm_msgs/SetJointsPositionRequest";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handsfree_arm_msgs/arm_joints_position data\n\
\n\
================================================================================\n\
MSG: handsfree_arm_msgs/arm_joints_position\n\
float32[] position #arm position\n\
";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointsPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::handsfree_arm_msgs::SetJointsPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::handsfree_arm_msgs::arm_joints_position_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTSPOSITIONREQUEST_H
