// Generated by gencpp from file handsfree_arm_msgs/SetJointPositionRequest.msg
// DO NOT EDIT!


#ifndef HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTPOSITIONREQUEST_H
#define HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace handsfree_arm_msgs
{
template <class ContainerAllocator>
struct SetJointPositionRequest_
{
  typedef SetJointPositionRequest_<ContainerAllocator> Type;

  SetJointPositionRequest_()
    : id(0)
    , position(0.0)  {
    }
  SetJointPositionRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , position(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef float _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointPositionRequest_

typedef ::handsfree_arm_msgs::SetJointPositionRequest_<std::allocator<void> > SetJointPositionRequest;

typedef boost::shared_ptr< ::handsfree_arm_msgs::SetJointPositionRequest > SetJointPositionRequestPtr;
typedef boost::shared_ptr< ::handsfree_arm_msgs::SetJointPositionRequest const> SetJointPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace handsfree_arm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'handsfree_arm_msgs': ['/home/handsfree/handsfree/handsfree_ros_ws/src/handsfree_arm/handsfree_arm_msgs/msg', '/home/handsfree/handsfree/handsfree_ros_ws/devel/share/handsfree_arm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34da3b42c9f93d7d1f000179528cfe5e";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34da3b42c9f93d7dULL;
  static const uint64_t static_value2 = 0x1f000179528cfe5eULL;
};

template<class ContainerAllocator>
struct DataType< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handsfree_arm_msgs/SetJointPositionRequest";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint8 id\n\
float32 position\n\
\n\
";
  }

  static const char* value(const ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::handsfree_arm_msgs::SetJointPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANDSFREE_ARM_MSGS_MESSAGE_SETJOINTPOSITIONREQUEST_H
