; Auto-generated. Do not edit!


(cl:in-package handsfree_arm_msgs-msg)


;//! \htmlinclude ArmBehaviorFeedback.msg.html

(cl:defclass <ArmBehaviorFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback_bool
    :reader feedback_bool
    :initarg :feedback_bool
    :type cl:float
    :initform 0.0))
)

(cl:defclass ArmBehaviorFeedback (<ArmBehaviorFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArmBehaviorFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArmBehaviorFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name handsfree_arm_msgs-msg:<ArmBehaviorFeedback> is deprecated: use handsfree_arm_msgs-msg:ArmBehaviorFeedback instead.")))

(cl:ensure-generic-function 'feedback_bool-val :lambda-list '(m))
(cl:defmethod feedback_bool-val ((m <ArmBehaviorFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader handsfree_arm_msgs-msg:feedback_bool-val is deprecated.  Use handsfree_arm_msgs-msg:feedback_bool instead.")
  (feedback_bool m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArmBehaviorFeedback>) ostream)
  "Serializes a message object of type '<ArmBehaviorFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'feedback_bool))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArmBehaviorFeedback>) istream)
  "Deserializes a message object of type '<ArmBehaviorFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'feedback_bool) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArmBehaviorFeedback>)))
  "Returns string type for a message object of type '<ArmBehaviorFeedback>"
  "handsfree_arm_msgs/ArmBehaviorFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArmBehaviorFeedback)))
  "Returns string type for a message object of type 'ArmBehaviorFeedback"
  "handsfree_arm_msgs/ArmBehaviorFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArmBehaviorFeedback>)))
  "Returns md5sum for a message object of type '<ArmBehaviorFeedback>"
  "adcf7c34a058504c0b38f31ca66f0395")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArmBehaviorFeedback)))
  "Returns md5sum for a message object of type 'ArmBehaviorFeedback"
  "adcf7c34a058504c0b38f31ca66f0395")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArmBehaviorFeedback>)))
  "Returns full string definition for message of type '<ArmBehaviorFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback defin~%float64 feedback_bool~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArmBehaviorFeedback)))
  "Returns full string definition for message of type 'ArmBehaviorFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback defin~%float64 feedback_bool~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArmBehaviorFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArmBehaviorFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ArmBehaviorFeedback
    (cl:cons ':feedback_bool (feedback_bool msg))
))
