// Generated by gencpp from file handsfree_msgs/GetParamList.msg
// DO NOT EDIT!


#ifndef HANDSFREE_MSGS_MESSAGE_GETPARAMLIST_H
#define HANDSFREE_MSGS_MESSAGE_GETPARAMLIST_H

#include <ros/service_traits.h>


#include <handsfree_msgs/GetParamListRequest.h>
#include <handsfree_msgs/GetParamListResponse.h>


namespace handsfree_msgs
{

struct GetParamList
{

typedef GetParamListRequest Request;
typedef GetParamListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetParamList
} // namespace handsfree_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handsfree_msgs::GetParamList > {
  static const char* value()
  {
    return "1dbbb9344d5148e4dc17b3b0135d5f58";
  }

  static const char* value(const ::handsfree_msgs::GetParamList&) { return value(); }
};

template<>
struct DataType< ::handsfree_msgs::GetParamList > {
  static const char* value()
  {
    return "handsfree_msgs/GetParamList";
  }

  static const char* value(const ::handsfree_msgs::GetParamList&) { return value(); }
};


// service_traits::MD5Sum< ::handsfree_msgs::GetParamListRequest> should match 
// service_traits::MD5Sum< ::handsfree_msgs::GetParamList > 
template<>
struct MD5Sum< ::handsfree_msgs::GetParamListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_msgs::GetParamList >::value();
  }
  static const char* value(const ::handsfree_msgs::GetParamListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_msgs::GetParamListRequest> should match 
// service_traits::DataType< ::handsfree_msgs::GetParamList > 
template<>
struct DataType< ::handsfree_msgs::GetParamListRequest>
{
  static const char* value()
  {
    return DataType< ::handsfree_msgs::GetParamList >::value();
  }
  static const char* value(const ::handsfree_msgs::GetParamListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handsfree_msgs::GetParamListResponse> should match 
// service_traits::MD5Sum< ::handsfree_msgs::GetParamList > 
template<>
struct MD5Sum< ::handsfree_msgs::GetParamListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_msgs::GetParamList >::value();
  }
  static const char* value(const ::handsfree_msgs::GetParamListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_msgs::GetParamListResponse> should match 
// service_traits::DataType< ::handsfree_msgs::GetParamList > 
template<>
struct DataType< ::handsfree_msgs::GetParamListResponse>
{
  static const char* value()
  {
    return DataType< ::handsfree_msgs::GetParamList >::value();
  }
  static const char* value(const ::handsfree_msgs::GetParamListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDSFREE_MSGS_MESSAGE_GETPARAMLIST_H
