// Generated by gencpp from file handsfree_msgs/SpecialMoveRequest.msg
// DO NOT EDIT!


#ifndef HANDSFREE_MSGS_MESSAGE_SPECIALMOVEREQUEST_H
#define HANDSFREE_MSGS_MESSAGE_SPECIALMOVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace handsfree_msgs
{
template <class ContainerAllocator>
struct SpecialMoveRequest_
{
  typedef SpecialMoveRequest_<ContainerAllocator> Type;

  SpecialMoveRequest_()
    : target_distance_move(0.0)  {
    }
  SpecialMoveRequest_(const ContainerAllocator& _alloc)
    : target_distance_move(0.0)  {
  (void)_alloc;
    }



   typedef float _target_distance_move_type;
  _target_distance_move_type target_distance_move;





  typedef boost::shared_ptr< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpecialMoveRequest_

typedef ::handsfree_msgs::SpecialMoveRequest_<std::allocator<void> > SpecialMoveRequest;

typedef boost::shared_ptr< ::handsfree_msgs::SpecialMoveRequest > SpecialMoveRequestPtr;
typedef boost::shared_ptr< ::handsfree_msgs::SpecialMoveRequest const> SpecialMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace handsfree_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'handsfree_msgs': ['/home/handsfree/handsfree/handsfree_ros_ws/src/handsfree/handsfree_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08049cf88f7884e57eea58fec5dbb071";
  }

  static const char* value(const ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08049cf88f7884e5ULL;
  static const uint64_t static_value2 = 0x7eea58fec5dbb071ULL;
};

template<class ContainerAllocator>
struct DataType< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handsfree_msgs/SpecialMoveRequest";
  }

  static const char* value(const ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 target_distance_move\n\
";
  }

  static const char* value(const ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_distance_move);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpecialMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::handsfree_msgs::SpecialMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "target_distance_move: ";
    Printer<float>::stream(s, indent + "  ", v.target_distance_move);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANDSFREE_MSGS_MESSAGE_SPECIALMOVEREQUEST_H
