// Generated by gencpp from file handsfree_msgs/SpecialTurn.msg
// DO NOT EDIT!


#ifndef HANDSFREE_MSGS_MESSAGE_SPECIALTURN_H
#define HANDSFREE_MSGS_MESSAGE_SPECIALTURN_H

#include <ros/service_traits.h>


#include <handsfree_msgs/SpecialTurnRequest.h>
#include <handsfree_msgs/SpecialTurnResponse.h>


namespace handsfree_msgs
{

struct SpecialTurn
{

typedef SpecialTurnRequest Request;
typedef SpecialTurnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpecialTurn
} // namespace handsfree_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handsfree_msgs::SpecialTurn > {
  static const char* value()
  {
    return "73c6e8bc92a2aaf25662afbf9779642b";
  }

  static const char* value(const ::handsfree_msgs::SpecialTurn&) { return value(); }
};

template<>
struct DataType< ::handsfree_msgs::SpecialTurn > {
  static const char* value()
  {
    return "handsfree_msgs/SpecialTurn";
  }

  static const char* value(const ::handsfree_msgs::SpecialTurn&) { return value(); }
};


// service_traits::MD5Sum< ::handsfree_msgs::SpecialTurnRequest> should match 
// service_traits::MD5Sum< ::handsfree_msgs::SpecialTurn > 
template<>
struct MD5Sum< ::handsfree_msgs::SpecialTurnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_msgs::SpecialTurn >::value();
  }
  static const char* value(const ::handsfree_msgs::SpecialTurnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_msgs::SpecialTurnRequest> should match 
// service_traits::DataType< ::handsfree_msgs::SpecialTurn > 
template<>
struct DataType< ::handsfree_msgs::SpecialTurnRequest>
{
  static const char* value()
  {
    return DataType< ::handsfree_msgs::SpecialTurn >::value();
  }
  static const char* value(const ::handsfree_msgs::SpecialTurnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handsfree_msgs::SpecialTurnResponse> should match 
// service_traits::MD5Sum< ::handsfree_msgs::SpecialTurn > 
template<>
struct MD5Sum< ::handsfree_msgs::SpecialTurnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handsfree_msgs::SpecialTurn >::value();
  }
  static const char* value(const ::handsfree_msgs::SpecialTurnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handsfree_msgs::SpecialTurnResponse> should match 
// service_traits::DataType< ::handsfree_msgs::SpecialTurn > 
template<>
struct DataType< ::handsfree_msgs::SpecialTurnResponse>
{
  static const char* value()
  {
    return DataType< ::handsfree_msgs::SpecialTurn >::value();
  }
  static const char* value(const ::handsfree_msgs::SpecialTurnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDSFREE_MSGS_MESSAGE_SPECIALTURN_H
