(cl:in-package handsfree_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LOCAL_TIME_VALID-VAL
          LOCAL_TIME_VALID
          LOCAL_TIME_YEAR-VAL
          LOCAL_TIME_YEAR
          LOCAL_TIME_MONTH-VAL
          LOCAL_TIME_MONTH
          LOCAL_TIME_DATE-VAL
          LOCAL_TIME_DATE
          LOCAL_TIME_WEEK-VAL
          LOCAL_TIME_WEEK
          LOCAL_TIME_HOUR-VAL
          LOCAL_TIME_HOUR
          LOCAL_TIME_MIN-VAL
          LOCAL_TIME_MIN
          LOCAL_TIME_SEC-VAL
          LOCAL_TIME_SEC
          WORK_TIME1_SEC-VAL
          WORK_TIME1_SEC
          WORK_TIME1_MIN-VAL
          WORK_TIME1_MIN
          WORK_TIME1_HOUR-VAL
          WORK_TIME1_HOUR
          WORK_TIME2_SEC-VAL
          WORK_TIME2_SEC
          WORK_TIME2_MIN-VAL
          WORK_TIME2_MIN
          WORK_TIME2_HOUR-VAL
          WORK_TIME2_HOUR
))