(cl:defpackage handsfree_msgs-srv
  (:use )
  (:export
   "GETPARAMLIST"
   "<GETPARAMLIST-REQUEST>"
   "GETPARAMLIST-REQUEST"
   "<GETPARAMLIST-RESPONSE>"
   "GETPARAMLIST-RESPONSE"
   "SETPARAMLIST"
   "<SETPARAMLIST-REQUEST>"
   "SETPARAMLIST-REQUEST"
   "<SETPARAMLIST-RESPONSE>"
   "SETPARAMLIST-RESPONSE"
   "SPECIALMOVE"
   "<SPECIALMOVE-REQUEST>"
   "SPECIALMOVE-REQUEST"
   "<SPECIALMOVE-RESPONSE>"
   "SPECIALMOVE-RESPONSE"
   "SPECIALTURN"
   "<SPECIALTURN-REQUEST>"
   "SPECIALTURN-REQUEST"
   "<SPECIALTURN-RESPONSE>"
   "SPECIALTURN-RESPONSE"
  ))

